upstream self_management_service {
    least_conn;
    server self_management_1:8080;
    server self_management_2:8080;
}

server {
    listen 80;

    location /self_management/ {
        proxy_pass http://self_management_service/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}