upstream self_management_service {
    least_conn;
    server self_management_1:8080;
    server self_management_2:8080;
}

upstream narcos_service {
    least_conn;
    server narcos_1:8080;
}

server {
    listen 80;

    location /self_management/ {
        rewrite ^/self_management/(.*)$ /$1 break;
        proxy_pass http://self_management_service/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

   location /narcos_team/ {
       rewrite ^/narcos_team/(.*)$ /$1 break;
       proxy_pass http://narcos_service;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
   }
}