spring:
  profiles:
    active: local  # ← remove this line, values are directly here

  mail:
    host: smtp.gmail.com
    port: 587
    username: rafsun7774@gmail.com
    password: ygqritxseeiqqdqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #This is connecting the application with the rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

app:
  mail:
    from: rafsun7774@gmail.com
    from-name: "spring-mail"